#!/usr/bin/env node
// Parse V8 --print-bytecode output into a per-function allocation census.
//
//   node --allow-natives-syntax --print-bytecode --print-bytecode-filter='rerank' harness.cjs \
//     | node census.mjs
//
// Or pass dump files: node census.mjs bytecode-before.txt bytecode-after.txt

import { readFileSync } from "node:fs";

function readInput() {
  const files = process.argv.slice(2);
  if (files.length > 0) return files.map((f) => readFileSync(f, "utf8")).join("\n");
  return readFileSync(0, "utf8");
}

const OPS = [
  "CreateClosure",
  "CreateFunctionContext",
  "CreateEmptyArrayLiteral",
  "CreateArrayLiteral",
  "CreateObjectLiteral",
  "CreateRegExpLiteral",
];

const text = readInput();
const blocks = text.split(/\[generated bytecode for function: (\S+)/).slice(1);
const rows = [];
for (let i = 0; i < blocks.length; i += 2) {
  const name = blocks[i];
  const body = blocks[i + 1] ?? "";
  const counts = Object.fromEntries(OPS.map((op) => [op, (body.match(new RegExp(op, "g")) ?? []).length]));
  const length = (body.match(/Bytecode length: (\d+)/) ?? [])[1] ?? "?";
  rows.push({ name, length, ...counts });
}

if (rows.length === 0) {
  console.error("no '[generated bytecode for function: ...]' blocks found (did you pass --print-bytecode?)");
  process.exit(1);
}

const columns = ["function", "len", "closures", "contexts", "arr[]", "obj{}"];
const data = rows.map((r) => [
  r.name,
  r.length,
  r.CreateClosure,
  r.CreateFunctionContext,
  r.CreateEmptyArrayLiteral + r.CreateArrayLiteral,
  r.CreateObjectLiteral,
]);
const widths = columns.map((c, i) => Math.max(c.length, ...data.map((d) => String(d[i]).length)));
const line = (cells) => cells.map((c, i) => String(c).padEnd(widths[i])).join(" ");
console.log(line(columns));
console.log(widths.map((w) => "-".repeat(w)).join(" "));
for (const row of data) console.log(line(row));

const totalClosures = rows.reduce((a, r) => a + r.CreateClosure + r.CreateFunctionContext, 0);
console.log(`\n${rows.length} function(s), ${totalClosures} closure/context allocations per call`);
