#!/usr/bin/env node
// Parse V8 --print-bytecode output into a per-function allocation census.
//
//   node --allow-natives-syntax --print-bytecode --print-bytecode-filter='rerank' harness.cjs \
//     | node census.mjs
//
// Or pass dump files: node census.mjs before.txt after.txt
// Add --json for machine-readable output to gate in CI.
//
// Counts are static construction sites in Ignition bytecode, not dynamic
// allocations. Cross-check allocation claims with --heap-prof or a heap
// snapshot delta (see references/memory-and-heap.md).

import { readFileSync } from "node:fs";

const args = process.argv.slice(2);
const asJson = args.includes("--json");
const files = args.filter((arg) => arg !== "--json");

function readInput() {
  if (files.length > 0) return files.map((f) => readFileSync(f, "utf8")).join("\n");
  return readFileSync(0, "utf8");
}

const COLUMNS = [
  ["closures", ["CreateClosure"]],
  ["contexts", ["CreateFunctionContext"]],
  ["arr[]", ["CreateEmptyArrayLiteral", "CreateArrayLiteral"]],
  ["obj{}", ["CreateObjectLiteral", "CreateEmptyObjectLiteral"]],
  ["re{}", ["CreateRegExpLiteral"]],
];
const KNOWN = new Set(COLUMNS.flatMap(([, ops]) => ops));

const text = readInput();
const blocks = text.split(/\[generated bytecode for function:\s*(\S+)/).slice(1);
const rows = [];
const unmapped = new Set();
for (let i = 0; i < blocks.length; i += 2) {
  let name = blocks[i];
  if (name.startsWith("(")) name = "(anonymous)";
  const body = (blocks[i + 1] ?? "").replaceAll("CreateFunctionContextWithCells", "CreateFunctionContext");
  const ops = {};
  for (const op of body.match(/\bCreate\w+/g) ?? []) ops[op] = (ops[op] ?? 0) + 1;
  for (const op of Object.keys(ops)) if (!KNOWN.has(op)) unmapped.add(op);
  const counts = Object.fromEntries(
    COLUMNS.map(([label, names]) => [label, names.reduce((sum, op) => sum + (ops[op] ?? 0), 0)])
  );
  const lengthMatch = body.match(/Bytecode length: (\d+)/);
  if (!lengthMatch) {
    console.error(`census: ${name} has no 'Bytecode length' line, the dump format may have changed`);
  }
  rows.push({ name, length: lengthMatch ? Number(lengthMatch[1]) : null, ops, ...counts });
}

if (rows.length === 0) {
  console.error("no '[generated bytecode for function: ...]' blocks found (did you pass --print-bytecode?)");
  process.exit(1);
}

const totals = Object.fromEntries(
  COLUMNS.map(([label]) => [label, rows.reduce((sum, row) => sum + row[label], 0)])
);
const knownTotal = totals.closures + totals.contexts;

if (asJson) {
  console.log(
    JSON.stringify(
      { functions: rows, totals, closureContextSites: knownTotal, unmappedOps: [...unmapped] },
      null,
      2
    )
  );
  process.exit(0);
}

const header = ["function", "len", ...COLUMNS.map(([label]) => label)];
const data = rows.map((row) => [row.name, row.length ?? "?", ...COLUMNS.map(([label]) => row[label])]);
const widths = header.map((c, i) => Math.max(c.length, ...data.map((d) => String(d[i]).length)));
const line = (cells) => cells.map((c, i) => String(c).padEnd(widths[i])).join(" ");
console.log(line(header));
console.log(widths.map((w) => "-".repeat(w)).join(" "));
for (const row of data) console.log(line(row));

console.log(`\n${rows.length} function(s), ${knownTotal} closure/context construction sites`);
console.log("static sites per function body, not dynamic counts: a guarded site may never execute");
if (unmapped.size > 0) {
  console.log(`unmapped Create ops (not in any column): ${[...unmapped].join(", ")}`);
}
