#!/usr/bin/env node
// Parse V8 --print-bytecode output into a per-function allocation census.
//
//   node --allow-natives-syntax --print-bytecode --print-bytecode-filter='rerank' harness.cjs \
//     | node census.mjs
//
// Or pass dump files: node census.mjs before.txt after.txt
// Add --json for machine-readable output to gate in CI.
// Add --classes to print a second table with cost classes, protocol ops, and
// loop-site counts. --diff before.txt after.txt prints per-function class-count
// deltas; --diff --json emits {before, after, deltas} as per-function class maps.
//
// Opcodes are read only from disassembly lines, so strings that happen to
// contain "CreateClosure" or a function header cannot pollute the counts.
// Categories match by rule, so a new V8 name lands in the closest column or in
// `other` instead of being dropped. Exit code 1 means the dump could not be
// parsed, not that opcodes moved.
//
// Cost classes, first matching rule wins so related names stay together:
//   alloc      Create* / _Create*, CloneObject, GetTemplateObject
//   iterator   GetIterator, CallIterator, IteratorNext, IteratorClose
//   property   Lda/Sta/Get/Set/Define + Named|Keyed|Global|Context|Current|Super
//   call       Call*, Invoke*, Construct*
//   branch     Jump*, Test*
//   arithmetic Add|Sub|Mul|Div|Mod|Exp|Inc|Dec*, Bitwise*, Shift*, Ldar, Star,
//              Mov, and remaining Lda*/Sta* (constants, arguments, holes)
//   other      everything else, named in otherOps
// Intrinsic names such as _CreateJSGeneratorObject count as ops and class as
// allocations.
//
// A JumpLoop with a printed target "(0xADDR @ N)" closes a loop whose body is
// bytecode offsets [N, jumpLoopOffset]. InLoop counts are static construction
// sites inside any (possibly nested) loop body: candidates for per-iteration
// work. JumpLoop lines without a printed target count as no body.
//
// Counts are static construction sites in Ignition bytecode, not dynamic
// allocations. Cross-check allocation claims with --heap-prof or GC counts (see
// references/memory-and-heap.md). Self-test: node census.test.mjs.

import { readFileSync } from "node:fs";

const args = process.argv.slice(2);
const asJson = args.includes("--json");
const asClasses = args.includes("--classes");
const asDiff = args.includes("--diff");
const files = args.filter((arg) => !arg.startsWith("--"));

const RULES = [
  ["closures", (op) => op === "CreateClosure"],
  ["contexts", (op) => op.includes("Context")],
  ["arr[]", (op) => op.includes("Array") || op === "CreateRestParameter"],
  ["obj{}", (op) => /Object(Literal|FromIterable)/.test(op) || /MappedArguments|UnmappedArguments/.test(op) || op === "CloneObject"],
  ["re{}", (op) => op.includes("RegExp")],
];
const LABELS = RULES.map(([label]) => label);
const OTHER = "other";

const CLASS_LABELS = ["alloc", "call", "property", "iterator", "branch", "arithmetic", OTHER];
const CLASS_RULES = [
  ["alloc", (op) => op.startsWith("Create") || op.startsWith("_Create") || op === "CloneObject" || op === "GetTemplateObject"],
  ["iterator", (op) => /^(GetIterator|CallIterator|IteratorNext|IteratorClose)$/.test(op)],
  ["property", (op) => /^(Lda|Sta|Get|Set|Define)(Named|Keyed|Global|Context|Current|Super)/.test(op)],
  ["call", (op) => /^(Call|Invoke|Construct)/.test(op)],
  ["branch", (op) => /^(Jump|Test)/.test(op)],
  [
    "arithmetic",
    (op) =>
      op === "Ldar" ||
      op.startsWith("Star") ||
      op === "Mov" ||
      /^(Add|Sub|Mul|Div|Mod|Exp|Inc|Dec|Bitwise|Shift)/.test(op) ||
      /^(Lda|Sta)[A-Z]/.test(op)
  ]
];

const PROTOCOL_OPS = [
  "GetIterator",
  "CallIterator",
  "IteratorNext",
  "IteratorClose",
  "CreateArrayFromIterable",
  "CopyDataProperties",
  "CreateRestParameter",
  "GetTemplateObject",
  "CreateMappedArguments",
  "CloneObject"
];

const LOOP_KEYS = {
  closures: "closuresInLoop",
  contexts: "contextsInLoop",
  "arr[]": "arraysInLoop",
  "obj{}": "objectsInLoop",
  "re{}": "regexpsInLoop"
};
const LOOP_LABELS = ["closuresInLoop", "contextsInLoop", "arraysInLoop", "objectsInLoop", "regexpsInLoop", "protocolInLoop"];

const INSTRUCTION_RE = /@\s+(-?\d+)\s*:\s*(?:[0-9a-f]{2}\s+)*([A-Za-z][A-Za-z0-9_]*)([^\n]*)/g;
const LOOP_TARGET_RE = /@\s*(-?\d+)\s*\)/;

function classify(op) {
  const rule = CLASS_RULES.find(([, matches]) => matches(op));
  return rule ? rule[0] : OTHER;
}

function zeroed(labels) {
  return Object.fromEntries(labels.map((label) => [label, 0]));
}

function readInput() {
  if (files.length > 0) return files.map((f) => readFileSync(f, "utf8")).join("\n");
  return readFileSync(0, "utf8");
}

function parse(text) {
  const blockRe = /^\[generated bytecode for function:[ \t]*(.*?)(?: \(0x[0-9a-f]+.*?)?\]\s*$/gm;
  const blocks = [...text.matchAll(blockRe)];
  const rows = [];
  let formatIssues = 0;

  for (let index = 0; index < blocks.length; index++) {
    const raw = blocks[index][1];
    const name = raw.startsWith("(") ? "(anonymous)" : raw;
    const start = blocks[index].index + blocks[index][0].length;
    const end = index + 1 < blocks.length ? blocks[index + 1].index : text.length;
    const body = text.slice(start, end);

    const ops = {};
    const instructions = [];
    for (const [, offset, mnemonic, operands] of body.matchAll(INSTRUCTION_RE)) {
      ops[mnemonic] = (ops[mnemonic] ?? 0) + 1;
      for (const intrinsic of operands.match(/_Create\w+/g) ?? []) {
        ops[intrinsic] = (ops[intrinsic] ?? 0) + 1;
      }
      instructions.push({ offset: Number(offset), mnemonic, operands });
    }

    const counts = zeroed(LABELS);
    const otherOps = [];
    for (const [op, count] of Object.entries(ops)) {
      if (!op.startsWith("Create") && !op.startsWith("_Create") && op !== "CloneObject") continue;
      const rule = RULES.find(([, matches]) => matches(op));
      if (rule) counts[rule[0]] += count;
      else otherOps.push(op);
    }
    counts[OTHER] = otherOps.reduce((sum, op) => sum + ops[op], 0);

    const classes = zeroed(CLASS_LABELS);
    for (const [op, count] of Object.entries(ops)) classes[classify(op)] += count;

    const protocol = Object.fromEntries(PROTOCOL_OPS.map((op) => [op, ops[op] ?? 0]));

    const loopBodies = [];
    for (const instruction of instructions) {
      if (instruction.mnemonic !== "JumpLoop") continue;
      const target = instruction.operands.match(LOOP_TARGET_RE);
      if (target) loopBodies.push([Number(target[1]), instruction.offset]);
    }
    const inLoop = (offset) => loopBodies.some(([from, to]) => offset >= from && offset <= to);

    const loopCounts = zeroed(LOOP_LABELS);
    for (const instruction of instructions) {
      if (!inLoop(instruction.offset)) continue;
      const names = [instruction.mnemonic, ...(instruction.operands.match(/_Create\w+/g) ?? [])];
      for (const op of names) {
        const rule = RULES.find(([, matches]) => matches(op));
        if (rule) loopCounts[LOOP_KEYS[rule[0]]] += 1;
      }
      if (PROTOCOL_OPS.includes(instruction.mnemonic)) loopCounts.protocolInLoop += 1;
    }

    const lengthMatch = body.match(/^Bytecode length: (\d+)/m);
    if (!lengthMatch) {
      console.error(`census: ${name} has no 'Bytecode length' line, the dump format may have changed`);
      formatIssues += 1;
    }
    rows.push({
      name,
      length: lengthMatch ? Number(lengthMatch[1]) : null,
      ops,
      otherOps,
      ...counts,
      classes,
      protocol,
      loopBodies: loopBodies.length,
      ...loopCounts
    });
  }

  return { rows, formatIssues };
}

function classMap(rows) {
  const map = {};
  for (const row of rows) {
    if (!map[row.name]) map[row.name] = zeroed(CLASS_LABELS);
    for (const label of CLASS_LABELS) map[row.name][label] += row.classes[label];
  }
  return map;
}

function printTable(header, data) {
  const widths = header.map((cell, i) => Math.max(cell.length, ...data.map((row) => String(row[i]).length)));
  const line = (cells) => cells.map((cell, i) => String(cell).padEnd(widths[i])).join(" ");
  console.log(line(header));
  console.log(widths.map((w) => "-".repeat(w)).join(" "));
  for (const row of data) console.log(line(row));
}

if (asDiff) {
  if (files.length !== 2) {
    console.error("census: --diff needs exactly two dump files: node census.mjs --diff before.txt after.txt");
    process.exit(1);
  }
  const beforeParsed = parse(readFileSync(files[0], "utf8"));
  const afterParsed = parse(readFileSync(files[1], "utf8"));
  if (beforeParsed.rows.length === 0 || afterParsed.rows.length === 0) {
    console.error("no '[generated bytecode for function: ...]' blocks found in one of the dumps (did you pass --print-bytecode?)");
    process.exit(1);
  }

  const before = classMap(beforeParsed.rows);
  const after = classMap(afterParsed.rows);
  const deltas = {};
  for (const name of new Set([...Object.keys(before), ...Object.keys(after)])) {
    const delta = {};
    let changed = false;
    for (const label of CLASS_LABELS) {
      const change = (after[name]?.[label] ?? 0) - (before[name]?.[label] ?? 0);
      if (change !== 0) {
        delta[label] = change;
        changed = true;
      }
    }
    if (changed) deltas[name] = delta;
  }

  if (asJson) {
    console.log(JSON.stringify({ before, after, deltas }, null, 2));
  } else {
    const sums = zeroed(CLASS_LABELS);
    const data = Object.entries(deltas).map(([name, delta]) => [
      name,
      ...CLASS_LABELS.map((label) => {
        const value = delta[label] ?? 0;
        sums[label] += value;
        return value > 0 ? `+${value}` : String(value);
      })
    ]);
    data.push(["totals", ...CLASS_LABELS.map((label) => (sums[label] > 0 ? `+${sums[label]}` : String(sums[label])))]);
    printTable(["function", ...CLASS_LABELS], data);
  }
  process.exit(beforeParsed.formatIssues + afterParsed.formatIssues > 0 ? 1 : 0);
}

const { rows, formatIssues } = parse(readInput());

if (rows.length === 0) {
  console.error("no '[generated bytecode for function: ...]' blocks found (did you pass --print-bytecode?)");
  process.exit(1);
}

const totals = Object.fromEntries(
  [...LABELS, OTHER].map((label) => [label, rows.reduce((sum, row) => sum + row[label], 0)])
);
totals.protocol = Object.fromEntries(
  PROTOCOL_OPS.map((op) => [op, rows.reduce((sum, row) => sum + row.protocol[op], 0)])
);
const classTotals = Object.fromEntries(
  CLASS_LABELS.map((label) => [label, rows.reduce((sum, row) => sum + row.classes[label], 0)])
);
const otherOps = [...new Set(rows.flatMap((row) => row.otherOps))];

if (asJson) {
  console.log(
    JSON.stringify(
      {
        functions: rows,
        totals,
        classTotals,
        otherOps,
        v8: process.versions.v8,
        node: process.version
      },
      null,
      2
    )
  );
  process.exit(formatIssues > 0 ? 1 : 0);
}

const header = ["function", "len", ...LABELS, OTHER];
const data = rows.map((row) => [row.name, row.length ?? "?", ...LABELS.map((label) => row[label]), row[OTHER]]);
printTable(header, data);

if (asClasses) {
  const classHeader = ["function", ...CLASS_LABELS, ...PROTOCOL_OPS, "loops", ...LOOP_LABELS];
  const classData = rows.map((row) => [
    row.name,
    ...CLASS_LABELS.map((label) => row.classes[label]),
    ...PROTOCOL_OPS.map((op) => row.protocol[op]),
    row.loopBodies,
    ...LOOP_LABELS.map((label) => row[label])
  ]);
  console.log("");
  printTable(classHeader, classData);
}

const closureContextSites = totals.closures + totals.contexts;
console.log(`\n${rows.length} function(s), ${closureContextSites} closure/context construction sites`);
console.log("rule-based columns: closures, contexts, arrays, objects, regexps, other");
console.log("static sites per function body, not dynamic counts: a guarded site may never execute");
console.log(`v8 ${process.versions.v8}, node ${process.version}`);
if (otherOps.length > 0) {
  console.log(`other Create ops (not closures, contexts, arrays, objects, regexps): ${otherOps.join(", ")}`);
}
if (formatIssues > 0) process.exitCode = 1;
