#!/usr/bin/env node
// Self-test for census.mjs. Run: node census.test.mjs
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const census = fileURLToPath(new URL("./census.mjs", import.meta.url));
const failures = [];

function run(input, args = ["--json"]) {
  return spawnSync(process.execPath, [census, ...args], { input, encoding: "utf8" });
}
function check(name, condition, detail = "") {
  if (!condition) failures.push(`${name}${detail ? `: ${detail}` : ""}`);
}

const full = `[generated bytecode for function: demo]
Bytecode length: 42
 @ 0 : 8b 00 00 02 CreateClosure
 @ 2 : 8f 00 01 CreateFunctionContextWithCells
 @ 4 : 85 CreateArrayFromIterable
 @ 6 : 84 CreateObjectLiteral
 @ 8 : 86 CreateRegExpLiteral
 @ 10 : 87 CreateGeneratorObject
`;
const parsed = JSON.parse(run(full).stdout);
const fn = parsed.functions[0];
check("closures", fn.closures === 1, JSON.stringify(fn));
check("contexts with WithCells suffix", fn.contexts === 1, JSON.stringify(fn));
check("CreateArrayFromIterable counts as arr[]", fn["arr[]"] === 1, JSON.stringify(fn));
check("obj{}", fn["obj{}"] === 1, JSON.stringify(fn));
check("re{}", fn["re{}"] === 1, JSON.stringify(fn));
check("unknown op lands in other", fn.other === 1, JSON.stringify(fn));
check("unknown op is listed", parsed.otherOps.includes("CreateGeneratorObject"), JSON.stringify(parsed.otherOps));
check("clean dump exits 0", run(full).status === 0);

const tricky = `[generated bytecode for function: get value]
Bytecode length: 99
 @ 0 : 8b CreateClosure
 @ 2 : 85 CreateRestParameter
 @ 4 : 86 CreateMappedArguments
 @ 6 : 87 CloneObject
 @ 8 : 89 InvokeIntrinsic [_CreateJSGeneratorObject], [0]
 @ 10 : 8a LdaConstant [0: "string with CreateClosure and [generated bytecode for function: phantom"]
`;
const trickyParsed = JSON.parse(run(tricky).stdout);
const trickyFn = trickyParsed.functions[0];
check("string content does not create a block", trickyParsed.functions.length === 1, JSON.stringify(trickyParsed.functions.map((f) => f.name)));
check("accessor name keeps its space", trickyFn.name === "get value", trickyFn.name);
check("CreateRestParameter counts as arr[]", trickyFn["arr[]"] === 1, JSON.stringify(trickyFn));
check("arguments objects count as obj{}", trickyFn["obj{}"] === 2, JSON.stringify(trickyFn));
check("intrinsic allocation is counted", trickyFn.other === 1 && trickyParsed.otherOps.includes("_CreateJSGeneratorObject"), JSON.stringify(trickyParsed.otherOps));
check("decoy string does not add closures", trickyFn.closures === 1, JSON.stringify(trickyFn));
check("tricky dump exits 0", run(tricky).status === 0);

const empty = run("no bytecode here");
check("no blocks exits 1", empty.status === 1);

const broken = `[generated bytecode for function: broken]
 CreateClosure
`;
const brokenRun = run(broken);
check("missing length exits 1", brokenRun.status === 1);
check("missing length is reported", brokenRun.stderr.includes("Bytecode length"), brokenRun.stderr);

const classesDump = `[generated bytecode for function: classes]
Bytecode length: 42
 @ 0 : 8b CreateClosure
 @ 2 : 8c CallUndefinedReceiver0
 @ 4 : 8d LdaNamedProperty
 @ 6 : 8e GetIterator
 @ 8 : 8f JumpIfTrue
 @ 10 : 90 Add
 @ 12 : 91 StackCheck
`;
const classesParsed = JSON.parse(run(classesDump).stdout);
const classFn = classesParsed.functions[0];
check("alloc class", classFn.classes.alloc === 1, JSON.stringify(classFn.classes));
check("call class", classFn.classes.call === 1, JSON.stringify(classFn.classes));
check("property class", classFn.classes.property === 1, JSON.stringify(classFn.classes));
check("iterator class", classFn.classes.iterator === 1, JSON.stringify(classFn.classes));
check("branch class", classFn.classes.branch === 1, JSON.stringify(classFn.classes));
check("arithmetic class", classFn.classes.arithmetic === 1, JSON.stringify(classFn.classes));
check("other class", classFn.classes.other === 1, JSON.stringify(classFn.classes));
check(
  "classTotals",
  classesParsed.classTotals.alloc === 1 && classesParsed.classTotals.arithmetic === 1,
  JSON.stringify(classesParsed.classTotals)
);

const loopsDump = `[generated bytecode for function: loops]
Bytecode length: 100
 @ 0 : 8a CreateClosure
 @ 10 : 8b CreateObjectLiteral
 @ 30 : 8c CreateClosure
 @ 50 : 8d GetIterator
 @ 88 : 8e JumpLoop [66], [0], [21] (0x1234 @ 22)
`;
const loopsFn = JSON.parse(run(loopsDump).stdout).functions[0];
check("loop body counted", loopsFn.loopBodies === 1, JSON.stringify(loopsFn));
check("allocation before target is not in loop", loopsFn.closuresInLoop === 1, JSON.stringify(loopsFn));
check("object before target is not in loop", loopsFn.objectsInLoop === 0, JSON.stringify(loopsFn));
check("protocol op in loop", loopsFn.protocolInLoop === 1, JSON.stringify(loopsFn));

const protocolDump = `[generated bytecode for function: protocol]
Bytecode length: 30
 @ 0 : 8a GetIterator a0, [1], [3]
 @ 4 : 8b IteratorNext
`;
const protocolParsed = JSON.parse(run(protocolDump).stdout);
const protocolFn = protocolParsed.functions[0];
check("GetIterator counted", protocolFn.protocol.GetIterator === 1, JSON.stringify(protocolFn.protocol));
check("IteratorNext counted", protocolFn.protocol.IteratorNext === 1, JSON.stringify(protocolFn.protocol));
check("protocol totals", protocolParsed.totals.protocol.GetIterator === 1, JSON.stringify(protocolParsed.totals.protocol));

const beforeDump = `[generated bytecode for function: changed]
Bytecode length: 20
 @ 0 : 8a CreateClosure
 @ 2 : 8b CallUndefinedReceiver0
[generated bytecode for function: stable]
Bytecode length: 10
 @ 0 : 8a CreateClosure
`;
const afterDump = `[generated bytecode for function: changed]
Bytecode length: 20
 @ 0 : 8a CreateClosure
 @ 2 : 8b Add
[generated bytecode for function: stable]
Bytecode length: 10
 @ 0 : 8a CreateClosure
`;
const dir = mkdtempSync(join(tmpdir(), "census-test-"));
const beforePath = join(dir, "before.txt");
const afterPath = join(dir, "after.txt");
writeFileSync(beforePath, beforeDump);
writeFileSync(afterPath, afterDump);
const diffRun = run("", ["--diff", "--json", beforePath, afterPath]);
check("diff json exits 0", diffRun.status === 0, diffRun.stderr);
const diffParsed = JSON.parse(diffRun.stdout);
check("diff call delta", diffParsed.deltas.changed.call === -1, JSON.stringify(diffParsed.deltas));
check("diff arithmetic delta", diffParsed.deltas.changed.arithmetic === 1, JSON.stringify(diffParsed.deltas));
check("diff omits unchanged function", diffParsed.deltas.stable === undefined, JSON.stringify(diffParsed.deltas));
check("diff keeps before functions", diffParsed.before.stable && diffParsed.before.stable.alloc === 1, JSON.stringify(diffParsed.before));
const diffHuman = run("", ["--diff", beforePath, afterPath]);
check(
  "diff human table exits 0",
  diffHuman.status === 0 && diffHuman.stdout.includes("changed") && diffHuman.stdout.includes("totals"),
  diffHuman.stdout
);
const diffArity = run("", ["--diff", beforePath]);
check("diff with one file exits 1", diffArity.status === 1, diffArity.stderr);
rmSync(dir, { recursive: true, force: true });

check("missing length exits 1 with --classes", run(broken, ["--classes"]).status === 1);

const plain = run(full, []);
check("default table keeps old columns", plain.status === 0 && plain.stdout.includes("closures") && !plain.stdout.includes("alloc"), plain.stdout);

if (failures.length > 0) {
  console.error(`census test: ${failures.length} failure(s)`);
  for (const failure of failures) console.error(`  ${failure}`);
  process.exit(1);
}
console.log("census test: all cases pass");
